# Generated by Django 3.0.3 on 2020-03-04 00:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200303_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='state',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
