# Generated by Django 3.0.3 on 2020-03-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200304_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=360)),
                ('movie_image', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
