# Generated by Django 3.0.3 on 2020-03-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_moviebackground'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviebackground',
            name='movie_image',
        ),
        migrations.AddField(
            model_name='moviebackground',
            name='movie_image_url',
            field=models.CharField(default='', max_length=360),
        ),
    ]
