# Generated by Django 3.0.3 on 2020-03-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200326_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='highest_rated_genre',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='highest_rated_movie',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='most_recent_movie',
            field=models.CharField(default='', max_length=30),
        ),
    ]
