# Generated by Django 3.0.2 on 2020-04-13 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200413_2103'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='mark',
            index_together=set(),
        ),
    ]
