# Generated by Django 3.0.2 on 2020-04-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200413_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='highest_rated_genre',
            new_name='highest_rated_show',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='movies_watched',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shows_watched',
            field=models.IntegerField(default=0),
        ),
    ]
