# Generated by Django 3.0.2 on 2020-04-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200414_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='def_image',
            field=models.ImageField(blank=True, upload_to='default_image'),
        ),
    ]
