# Generated by Django 3.0.2 on 2020-04-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_userprofile_def_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='most_recent_show',
            field=models.CharField(default='', max_length=30),
        ),
    ]
