# Generated by Django 3.0.2 on 2020-05-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200417_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
