# Generated by Django 3.0.2 on 2020-05-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_userprofile_def_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
