# Generated by Django 3.0.3 on 2020-05-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_mark_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviebackground',
            name='movie_image_url',
        ),
        migrations.AddField(
            model_name='moviebackground',
            name='movie_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
