# Generated by Django 3.0.6 on 2020-06-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_topten'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppWideImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_image', models.ImageField(blank=True, upload_to='default_image')),
                ('rotten_tomatoes_image', models.ImageField(blank=True, upload_to='default_image')),
            ],
        ),
    ]
