# Generated by Django 3.0.6 on 2020-06-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_appwideimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='highest_rated_movie',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='highest_rated_show',
        ),
    ]
